#!/usr/bin/env bash

path=`pwd`

mkdir ~/.config/nvim
ln -s $path/.gitconfig ~/.gitconfig
ln -s $path/.tmux.conf ~/.tmux.conf
ln -s $path/.zshrc ~/.zshrc
ln -s $path/init.vim ~/.config/nvim/init.vim

echo "Done!"
