#!/usr/bin/env bash

path=`pwd`

ln -s $path/.gemrc ~/.gemrc
ln -s $path/.gitconfig ~/.gitconfig
ln -s $path/.irbrc ~/.irbrc
ln -s $path/.tmux.conf ~/.tmux.conf
ln -s $path/.vimrc ~/.vimrc
ln -s $path/.zshrc ~/.zshrc

echo "Done!"
