#!/usr/bin/env bash

path=`pwd`

mkdir ~/.config/nvim
ln -s $path/gitconfig ~/.gitconfig
ln -s $path/tmux.conf ~/.tmux.conf
ln -s $path/zshrc ~/.zshrc
ln -s $path/init.vim ~/.config/nvim/init.vim
ln -s $path/redshift.conf ~/.config/redshift.conf
ln -s $path/kitty.conf ~/.config/kitty/kitty.conf

echo "Done!"
